### ISSUE TITLE
Create new widget for adding ancillary data

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#122]
Boundaries and Demographic Layers added from separate widget. 
- Separate widgets for Boundaries and Demographics 
- Fundamentally different than the other layers and are “overlaied” over ES layers. 
- When checked “on”, layers will be added to Active Layers list – same as if added from regular selection results list. 
- Some layers will be grouped to reduce total # of layers. 
- Dems will be from OEI(?)
- Hopefully BG level, if not, separate community dems. 

Boundaries:
- EnviroAtlas community boundaries
- HUC (4 Digit) Subregion
- HUC (8 Digit) Subbasin
- HUC (12 Digit) Subwatershed
- States
- Counties
- Block Groups
- Level III Ecoregions 
- Level IV Ecoregions 
- National Hydrography Dataset (NHDPLUS V2.1) 
- Protected Area Status
- Protected Area Stewardship
- EPA Impaired Waters Data

![image](https://cloud.githubusercontent.com/assets/2127036/14657922/87eba8e2-065e-11e6-9420-da61100bfd62.png)

**Comment by brosenbaum** [comment]
these are the "Spatially Explicit" layers in the config.json.... 
the last group in the list - rows 386 and higher.

There are additional services we can add that are not in the list - some of these are WMS/WFS services such as: 

https://nassgeodata.gmu.edu/CropScape/devhelp/help.html 

![image](https://cloud.githubusercontent.com/assets/6422486/17374815/3097b06a-5963-11e6-9ebf-e03243a56c19.png)

**Comment by brosenbaum** [comment]
or this: 

https://www.sciencebase.gov/arcgis/rest/services/Catalog/55b943ade4b09a3b01b65d78/MapServer

and this:

http://torka.unl.edu:8080/cgi-bin/mapserv.exe?map=/ms4w/apps/dm/service/usdm_current_wms.map&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=usdm_current&WIDTH=640&HEIGHT=480&srs=EPSG:4326&styles=default&format=image/png&bbox=-165,15,-60,80

**Comment by Baohong** [comment]
Could Barb or Torrin make a list of layer groups and specify which set of layers should be included in each group?

**Comment by brosenbaum** [comment]
will do - but I don't know if this has been completely finalized.
