### ISSUE TITLE
Package analytical tools in a drawer widget

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#145]
To reduce the number of on-screen buttons.

**Comment by David-Yarnell** [comment]
I asked about grouping on screen widgets on GeoNet. 
[https://geonet.esri.com/thread/179706](https://geonet.esri.com/thread/179706)

**Comment by torrin47** [comment]
Ouch, rscheitlin, that was a pretty harsh response.  Let's see if we can unpack it, though.
> you would need a custom code in the OnScreenWidgetIcon.js that would then call a custom menu like dijit for the user to choose which widget in the group to open
Sure, that makes sense, I think that's what we were anticipating - a menu digit that's triggered for the grouped widgets.
> not to talk about the work you would have to do to the Widget manager just for it to understand how to process on screen widget groups.
This is where I'm not sure I'm following - when Robert mentions the Widget Manager, is that the GUI builder application (which we could probably ignore), or is that some routine in the jimu.js code that handles widget lifecycle management (which we'd need to be careful about)?

**Comment by David-Yarnell** [comment]
I assumed he was talking about the WidgetManager class (jimu/WidgetManager.js).

**Comment by torrin47** [comment]
Makes sense (in 2.0 that's not a separate file, but the class is still
there in the jimu.js/main.js file) and I agree we want to mess with jimu as
little as possible but I must be missing the complexity WidgetManager must
already have code for grouping the panelwidgets - it does so automagically
as part of the responsive design. We ought to just be able to reuse that
code for our custom onscreenwidgets, right?

On Thu, Jul 14, 2016 at 12:14 PM, David Yarnell <notifications@github.com>
wrote:

> I assumed he was talking about the WidgetManager class
> (jimu/WidgetManager.js).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Innovate-Inc/EnviroAtlas/issues/145#issuecomment-232763931>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACB0vC_yNve8rx1PHoFF2wgDI3TZ2m33ks5qVoqIgaJpZM4In6dD>
> .
>



-- 
Torrin Hultgren
Senior Manager, Geospatial Solutions
Innovate!, Inc.
O:  (703) 922-9090 x737

http://www.innovateteam.com

Innovate!, Inc. is a Virginia-based 8(a), Hispanic- and woman-owned
business delivering Geospatial, Information Technology, Security,
Business Consulting, Project Management and Executive Coaching
solutions to our government and private sector clients.  Check us out
at www.innovateteam.com.

**Comment by David-Yarnell** [comment]
I am not seeing the on screen widgets grouping as part of the responsive design.

**Comment by torrin47** [comment]
Right - the onscreen widgets don't group, but the panel widgets do.  And
the code for that must be in WidgetManager, right?  Either that or the code
is in the template, but still relies on the same WidgetManager base.  My
thought process was that we could adapt the code written for panel widgets
to work for on-screen widgets, but in a designated way, rather than a
response to screen size.

On Thu, Jul 14, 2016 at 3:02 PM, David Yarnell <notifications@github.com>
wrote:

> I am not seeing the on screen widgets grouping as part of the responsive
> design.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Innovate-Inc/EnviroAtlas/issues/145#issuecomment-232805736>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACB0vPUuE5GkFXsq_CynWDqUUgXOxBHaks5qVrHegaJpZM4In6dD>
> .
>



-- 
Torrin Hultgren
Senior Manager, Geospatial Solutions
Innovate!, Inc.
O:  (703) 922-9090 x737

http://www.innovateteam.com

Innovate!, Inc. is a Virginia-based 8(a), Hispanic- and woman-owned
business delivering Geospatial, Information Technology, Security,
Business Consulting, Project Management and Executive Coaching
solutions to our government and private sector clients.  Check us out
at www.innovateteam.com.
