### ISSUE TITLE
Small changes to Add Data choices

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#213]
- [x] Change title of "Add Data" to "Add Online Data"
- [x] Change title of "Add File" to "Upload Data"
- [x] Remove "Add Service" widget

**Comment by torrin47** [comment]
Remaining questions...

In the Add Online Data, the first tab shown is "Search", and the user is presented with "ArcGISOnline" (a dropdown with only one option).  I'm on the fence about whether "Search" or "Add from URL" should be shown first by default, but if we're not giving them a choice of where to search from, we should hide the "ArcGISOnline" dropdown and show the search box initially.

Any way to enable SSO support for signing in to the "Add Data from Web Map" widget? In other Esri template apps it's been pretty straightforward to add the oAuthAppID.  Happy to discuss further.

**Comment by David-Yarnell** [comment]
It is totally possible to enable SSO. It just needs a appID.

**Comment by torrin47** [comment]
Awesome, thought it might possibly be that easy. You got that, or need me to do so? I've done it a bunch.

**Comment by David-Yarnell** [comment]
I can add the code. I guess we need to create an app in the GPO that is registered so we can get an appId. Not sure where you want that so maybe you could do that?

**Comment by torrin47** [comment]
Done.  AppID: S8P0zvjK2t50sCNd

Item:  https://epa.maps.arcgis.com/home/item.html?id=0b913b6a0ebb49839a9b594567ebc729
