### ISSUE TITLE
Create tile cache for all national layers

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#236]
Automate as possible.

**Comment by brosenbaum** [comment]
Moving along on this now - should have this completed by Thursday. 
We have caches created for many national layers - sort number 98 through 143 as of 2/6/17. 
All are in the following location: https://leb.epa.gov/arcgiscache_exp/

Service/folder names are layer names without spaces and removing anything in parenthesis "()" such as 
"Cultivated biological nitrogen fixation (kg N/ha/yr)" will be stored as "Cultivatedbiologicalnitrogenfixation"

Do we need to have another column in JSON file with this?

**Comment by brosenbaum** [comment]
Caches are complete and will be named as layer name - without spaces - and anything in "(" ")" will be ignored (this is what we did in flex for DFS names). If there is text in "[" "]" will be maintained. Currently, no national layers have "[" "]".

for example here is a snip of the directory listing:
![image](https://cloud.githubusercontent.com/assets/6422486/22899747/c81c01dc-f1e0-11e6-9781-0f1de0cb5b8c.png)

Do we need to add this to the JSON? or can this be coded... all the folders are in https://leb.epa.gov/arcgiscache_exp/

**Comment by brosenbaum** [comment]
have copied the caches to production - 

Service with all national metric layers is here: https://enviroatlas.epa.gov/arcgis/rest/services/Other/national_master/MapServer

caches for level 00 - 09 are here under the same format:
https://enviroatlas.epa.gov/arcgiscache_exp/ 

for example: https://enviroatlas.epa.gov/arcgiscache_exp/Cottonyields/_alllayers/L00/R00000000/C00000000.png
