### ISSUE TITLE
Create simple startup document for new developers

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#242]
Probably a good fit for the readme.md file in the root of the repository.  Should contain links to GitHub guidance on forking and pulling, using issues, and using zenhub.  Also point to Esri developer guidance on WAB widgets.

**Comment by brosenbaum** [comment]
[SourceTree-GitHub.pdf](https://github.com/Innovate-Inc/EnviroAtlas/files/717447/SourceTree-GitHub.pdf)

**Comment by brosenbaum** [comment]
Added to Wiki: https://github.com/Innovate-Inc/EnviroAtlas/wiki/Adding-code-to-the-repository-for-collaborators

Will add more in the readme wiki, also as per list above.

**Comment by brosenbaum** [comment]
Add more info to main wiki page - closing issue
