### ISSUE TITLE
Implement new topic selection in layer selection widget

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#279]
- [x] Update config.json to include topics. (Torrin)
- [ ] Move Geography selection to top
- [ ] Use topics instead of benefit categories - is there a reasonable way to make two columns but still have the topics themselves be derived from the json?

**Comment by Baohong** [comment]
Could you explain further in "is there a reasonable way to make two columns but still have the topics themselves be derived from the json?"

**Comment by brosenbaum** [comment]
[EAWAB4JSON_20161214.xlsx](https://github.com/Innovate-Inc/EnviroAtlas/files/658278/EAWAB4JSON_20161214.xlsx)

here is the latest version - supersedes the one in the email. Benefit cats are noted by X (the x's in each BC still may change - need review)
tabs for the three "TOC's" (EA_main, PBS, and Boundary) and one for all layers.

Some URLs are not yet finished - these are highlighted in red and are in the community list. These are cached services that are being created.

**Comment by torrin47** [comment]
@Baohong in one of their screenshots they showed two vertical columns of topics side by side as a way to fit a large number of topics in a tall, narrow screen space. I have previously struggled to format columns gracefully in HTML, and wasn't aware of a method to have the layout automatically have text flow gracefully from one column to the next. Fortunately, it looks like I just wasn't keeping up with the latest options in CSS - this property would seem to be what we need to get two columns of Topics side by side:
http://www.w3schools.com/css/css3_multiple_columns.asp
want to give it a try?

**Comment by torrin47** [comment]
@brosenbaum  Did I hear correctly yesterday that People and Built Spaces services are actually going to be moved out of the separate PBS sheet and into the EA_Main and become just another topic?  So the PBS sheet will end up being simply "demographics"?  Otherwise the sheet looks good, didn't require many updates to the script.

**Comment by torrin47** [comment]
scripts/config.json now has eaTopic and benefit categories have values of true (or not present).

**Comment by Baohong** [comment]
Search filter has been updated with topic selections available. The height of selectable layers has been adjusted --- height: calc(100% - 525px); height: -moz-calc(100% - 625px); height: -webkit-calc(100% - 525px); ----So for IE and firefox, there is different value for height. I set this way because I test from my local and IE and firefox need different value for height. Please test from your end.

**Comment by Baohong** [comment]
In config.json, there is a field "eaMetric": "boundary". Does that imply the layer is boundary?

**Comment by Baohong** [comment]
There is a problem with adding National layers to map. This is how it happens: Toggle on National and Toggle on all topics. The first layer in selectable layers is "Acres of land enrolled in CRP". There is no eaLyrNum for that layer in config.json.  
Similar problem could be found in boundary json file: the layer in boundary is "eaID": 917. There is no eaLyrNum  for that layer either.
