### ISSUE TITLE
Migrate popup configuration to spreadsheet. 

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#289]
Even though all the national layers share an identical popup configuration, the community, people and built spaces, and boundaries layers differ, so let's store the popup configuration as an attribute in the excel spreadsheet instead of hard-coding it in the script.  

The pattern for the national (HUC12) layer title is:

HUC 12 ID: {HUC_12}

Label is equal to the layer title and fieldName is equal to the mapped attribute - are there any layers for which this pattern does not hold?

**Comment by brosenbaum** [comment]
update to spreadsheet with corrected variable names.

[EAWAB4JSON_20170103.xlsx](https://github.com/Innovate-Inc/EnviroAtlas/files/686026/EAWAB4JSON_20170103.xlsx)

**Comment by torrin47** [comment]
Block Group ID: {GEOID10}
