### ISSUE TITLE
Undock Layer List Widget and make visible when any layer is selected

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#302]
We decided to move the layerList widget from the left panel to an onscreen floating widget (default position in the upper right), and in the same way that turning on a layer in the layerList widget automatically makes the Legend Widget visible if it isn't already showing, if a layer is selected in the simpleSearchFilter widget and the layerList widget isn't visible, show it.

**Comment by Baohong** [comment]
So simpleSearchFilter remains at current position, we just need to remove the layerList widget from the left panel. If a layer is selected in the simpleSearchFilter widget we need to automatically make the layerList applear on map (upper right). Is that correct? 
Do we need to make the layer turned on when added to map?

**Comment by torrin47** [comment]
Yes, that is correct to your first question.

To whether the layer needs to be turned on when added to the map, I'd like to hold off for now. Let's see how they react to seeing the layer being added to the floating widget. It's quite possible they'll still want the layer to be turned on, but I'd prefer to handle that as a separate discussion regarding all the different scenarios.

**Comment by Baohong** [comment]
Layer List Widget is now undocked and will be visible when any  layers in SimpleSearchFilter widget is selected.

**Comment by torrin47** [comment]
Awesome! Thanks for the quick turnaround, looks great to me, can't wait to hear what they say.
