### ISSUE TITLE
Update spreadsheet with final service names, topics

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#306]
Get all the data working (with the exception of PBS and Boundaries which RTP still needs to figure out)

Replace "individual layer" with service links for items like HUCs, NLCD, etc. These will be added as "whole services" for Boundaries.

**Comment by brosenbaum** [comment]
replaced all layers in boundary tab and a few in national (Ecoregions, Assessed/Impaired Waters, GAP, Wetlands) with service calls. Left the layer number blank for these services, and in EA_main, made the cells yellow in column J to highlight those changed.  

The "Species: At-Risk and Priority" rows in EA_main are these values from column A: 134-138, 151-155, 170-174, and 180-185.

If you don't want service calls in the EA_main, I can fix that - I left them in the "All (TopicInBC)" tab.

[EAWAB4JSON_20170118_services.xlsx](https://github.com/Innovate-Inc/EnviroAtlas/files/715421/EAWAB4JSON_20170118_services.xlsx)

**Comment by torrin47** [comment]
Updated config.json files, submitting pull request @Baohong please let us know if there are still issues, thanks!
