### ISSUE TITLE
Formatting items in Legend Widget

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#310]
- [ ] make whole widget smaller when initially open.
- [ ] If possible, change polygon to rectangle rather than "flag".
- [ ] Comment is: "Efficient use of space in legend" - may need some clarification

- [ ] (BJR added...) Layer names for single-feature legend items such as state boundaries. Maybe if legend layer label/title is empty, calc it = to layer name?  class="esriLegendLayerLabel"

**Comment by torrin47** [comment]
This issue was moved to USEPA/EnviroAtlas_JSApp#25
