### ISSUE TITLE
Make default extent full contiguous US (home button)

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#311]

**Comment by torrin47** [comment]
Huh? In what way is this not how it works today?

**Comment by brosenbaum** [comment]
I think it's slightly short of that - 1:~36mill scale covers most of the conterminous US. Next level out is where we want to be - level 3 (Scale: 7.3957190948944E7)

**Comment by torrin47** [comment]
That's going to be dependent on screen size.  We can't fix extent to a zoom level, only a geographic bounding box.  Esri autocalculates the right zoom level based on fit between screen size and geographic extent.  Which means it will be slightly different for everyone's screen.

**Comment by brosenbaum** [comment]
won't close until reviewed by others, but did make a pull request.

**Comment by brosenbaum** [comment]
New extent works well - need to reset home after sidebar widget opens on start to re-position the "US". shifts when sidebar opens. 

Also, are we changing the western extent to nor include so much of the Pacific?

**Comment by torrin47** [comment]
Yeah, my preference would be to try and limit the extent to as close as possible to the actual shoreline (with some rounding to the nearest degree) and let the browser worry about centering and determining zoom level.  If we try to play games with it, we'll never get it right with all browser sizes.

**Comment by torrin47** [comment]
Nix that, we're going to address this differently.
