### ISSUE TITLE
Filter Widget function change items

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#312]
- [ ] Add button/arrow/something in filter list at bottom to close or minimize the filter topics.
- [x] Total number of maps total filtered by geography. Currently "0 of 312".
- [x] Search bar: remove the word "Search", change to italic wording in bar to be either "Search all layers" or "Search within selected filters" (bjr suggestion: "Search filtered layers"?)
- [x] Select All Layers functionality:  1. if checked and user unchecks one layer, then Select all layers becomes unchecked.  2. if checked and user unchecks Select All Layers, the uncheck all layers.  3. if all layers are checked individually by user, then make Select All Layers checked.

**Comment by torrin47** [comment]
The geography selection toggles should also filter the list of layers - right now if no topics are selected, all of the layers are shown regardless of selected geography.

**Comment by jeremybaynes** [comment]
Number 2 done.  Number 1 requires a bit more work.  Not MVP since there is currently some visual clue that clicking the topic header does something.
