### ISSUE TITLE
Deploy (or restore) 1 or 2 tile caches for demonstration

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#326]
As discussed, let's get a couple of tile caches working like they were before, to ensure the code still works and the scale break is still where it should be, and be able to discuss options for communicating with the user about the lack of custom symbology at small scales.

**Comment by brosenbaum** [comment]
see issue #64. exported caches are still there.

If layer names are used instead of variable names, the names of the cache folders have been updated to match the layer names (but without spaces).

**Comment by torrin47** [comment]
Ok, caches may still be there, but I'm not seeing any attempt to fetch those tiles in the browser traffic - @Baohong, is this something you can investigate? Was the tile cache functionality from #64 broken by some other subsequent code change?

**Comment by Baohong** [comment]
Sure, will do.

**Comment by Baohong** [comment]
Previously, there were two tiled services:
Tiled service is:
	http://leb.epa.gov/arcgis/rest/services/test_services/Agriculturalwateruse/MapServer
	http://leb.epa.gov/arcgis/rest/services/test_services/Acresofcropsthathavenonearbypollinatorhabitat/MapServer

But when I add them to config.json as attribute tileLink, they cannot be added to map.

So I tested in sandbox using the code described in issue #64 , none of them works. 
I am wondering if I am using the correct tiled services.

**Comment by brosenbaum** [comment]
the path for the cached tiles are formated as this:
https://leb.epa.gov/arcgiscache_exp/Agriculturalwateruse/_alllayers/L06/R0000001a/C0000000e.png

and similarly for the renamed layer....

https://leb.epa.gov/arcgiscache_exp/Acresofpollinatedcropswithnonearbypollinatorhabitat/_alllayers/L01/R00000000/C00000000.png

**Comment by Baohong** [comment]
Thanks, Barb! They both works in ESRI sandbox.
