### ISSUE TITLE
Allow user to re-order layers that have already been added to the map

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#333]
Evaluate feasibility.

**Comment by jeremybaynes** [comment]
Would a possible work around for now be a "Move to Top" option in the popup?  I suppose it could just remove then re-add the layer since new layers are added to the top of the list.

Not ideal, but it may get us through until ESRI adds the functionality we're looking for.

Thoughts?

**Comment by torrin47** [comment]
Yes, seems like a reasonably compromise we could target for MVP.  Putting into the queue.

**Comment by Baohong** [comment]
"Move to Top" has replaced "Zoom to" in Layerlist.
