### ISSUE TITLE
Enable popup to work when tile cache is visible

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#343]
Mouse click should continue to query the underlying feature service, even at scales when the feature layer is not visible and the tile cache is displayed.

**Comment by brosenbaum** [comment]
Just a note: Sounds as though they will want some of the PBS layers to be web tile caches also.  this will be about 30 of the layers in the PBS tab...

**Comment by Baohong** [comment]
Popup info window is working for feature layers in LocalLayer widget. We can discuss PBS case in meeting.
There are still format problems, such as title for popup window is too long, also I need to set number of digit for the popup number according to config file.
