### ISSUE TITLE
Layers not displaying in WAB

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#361]
Some layers are not displaying in the operational list but are in the select/filter list. Ecoregions is one example, and there are others.

**Comment by brosenbaum** [comment]
will have a list of layer issues soon - and I will check the service URLs in the json file before passing this along for any code problems.

**Comment by brosenbaum** [comment]
Most of the cached community layers are not drawing in application and neither are many of the external services. I am checking the EAWAB4JSON.xlsx file and verifying the service link and layers. 

That said, the links for many of the national layers has not changed for a long time - neither has the community layers so they should be working.

The list of layers not working  are:

Community Layers:
Acute respiratory symptoms avoided due to ozone removed by tree cover (cases/yr)  (NOT Cached...)
Land cover
Tree cover configuration and connectivity
Estimated percent of tree cover within 26m of a road edge
Estimated tree cover in 15m stream and lake buffer (percent)
Estimated tree cover in 50m stream and lake buffer (percent)
Estimated vegetated cover in 15m stream and lake buffer (percent)
Estimated vegetated cover in 50m stream and lake buffer (percent)
Estimated walking distance to a park entrance (m)
Percent green space along walkable roads
Percent green space within 1/4 square kilometer
Percent impervious area within 1 square kilometer

National Layers:
Potential Wetland Area
Potentially Restorable Wetlands on Agricultural Land
Rare Ecosystems
USEPA Ecoregions (Omernik)
Landscape Conservation Cooperatives 
GAP Ecological Systems
GAP Status Code (Land Protection Status (GAP))
General Agency Level (Land Stewardship)
IUCN Category (Land Protection Status (IUCN))
Connectivity, Natural Land Cover 2006, Water Ignored
Connectivity, Natural Land Cover 2006, Water as Background
Connectivity, Natural Land Cover 2006, Water as Foreground
Land_Cover_2011_CONUS (NLCD_2011, National Land Cover Database (NLCD))
Land_Cover_1992 (NLCD_1992, National Land Cover Database (NLCD))
Land_Cover_2001_CONUS (NLCD_2001, National Land Cover Database (NLCD))
Land_Cover_2006_CONUS (NLCD_2006, National Land Cover Database (NLCD))
Soils Drainage Class - dominant condition
Impaired Waters
Assessed Waters
Wetlands
Watersheds - Projects [centroids]
Watersheds - Markets [centroids]
Watersheds - Projects [boundaries]
Watersheds - Local-scale Markets
Watersheds - Regional-scale Markets
Watersheds - State-scale Markets
Watersheds - National-scale Markets
Imperiled Species and Habitats - Projects [centroids]
Imperiled Species and Habitats - Markets [centroids]
Imperiled Species and Habitats - Projects [boundaries]
Imperiled Species and Habitats - Regional-scale Markets
Imperiled Species and Habitats - State-scale Markets
Imperiled Species and Habitats - National-scale Markets
Wetlands and Streams - Projects [centroids]
Wetlands and Streams - Markets [centroids]
Wetlands and Streams - Projects [boundaries]
Wetlands and Streams - Regional-scale Markets
Wetlands and Streams - State-scale Markets
Wetlands and Streams - National-scale Markets
Forest Carbon - Projects [centroids]
Forest Carbon - Markets [centroids]
Forest Carbon - State-scale Markets
Forest Carbon - National-scale Markets
Enabling Conditions - Watershed-scale
Enabling Conditions - State-scale
Enabling Conditions - Regional-scale
Enabling Conditions - Federal lands-scale
Enabling Conditions - National-scale
Enabling Conditions - National-scale

**Comment by torrin47** [comment]
Ok, for almost all of those (Acute Respiratory Symptoms seems to be the only exception) the common theme is that they don't have an attribute listed. I'm not sure why that would be fatal - we only use it for the popup configuration, but if having a null value in the popup is preventing the whole layer from being added, it should be straightforward to just completely suppress the popup for those layers - is that what we want?

**Comment by torrin47** [comment]
Updated script, waiting for new spreadsheet before committing.

**Comment by brosenbaum** [comment]
new spreadsheet sent #381

**Comment by brosenbaum** [comment]
discussion in #382

**Comment by brosenbaum** [comment]
Sue saw that tiled community service didn't load in layer list for engagement/estimated walking distance to a park entrance today....
