### ISSUE TITLE
Facilitate community selection when community layer is chosen

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#368]
We've discussed two main strategies for this.

1. When a community layer is selected, if a community is not also chosen, launch the "community selection" widget automatically to encourage/streamline selection of a community.  
2. Any time a community layer has been added to the table of contents, a point layer should also be shown on the map at all scales at which the community block group polygons are not shown. If a user clicks on a community, the popup will have brief information about that community along with a button to "select" the community which will trigger the zoom in and definition expression.

I really like option 2, but am coming to appreciate the complexity.  Thoughts?

_Editing this issue at the top level to be able to add the to-do checklist..._

The team and EPA consensus seems to be option 2.  Thinking out loud... that means that when someone selects a community layer and it's not already on the map, we would want the community points service to be automatically added to the map. Maybe others were already thinking along these lines, but what if we treat this community points service just like any other "boundaries" layer - and perhaps swap it out for the existing EnviroAtlas Community Boundaries service currently in the boundaries list?
The positive implications would be:

- As a boundary layer, this layer would always be drawn on top of other layers 
- As a boundary layer, whatever we agree upon for toggling visibility on and off would be consistent (either include in or suppress from Layer List widget) 
- A user could always turn this layer off, but whenever they add a new community layer, this layer would be turned on again (similar to how the Layer List and Legend widgets are automatically shown and can be closed again)
- A user could always turn this layer on independently via the boundaries widget

Any negatives? If we take this approach, the next steps would be:

- [ ] Finalize popups for the communities (descriptive paragraph? links to fact sheets?)
- [ ] Add map service to boundaries list

~~Add prominent "Select this community" button to the popup that has the same functionality as the Select Community widget~~

~~Add code that automatically triggers addition of this layer when a community layer is added to the map~~

**Comment by brosenbaum** [comment]
I agree with your second option - anything we can demo today? (just kidding!!!) The idea of the a popup is great so that links to the DataFactSheets - or even using the DFS text - can be helpful.
 
I made a service on leb of community poly boundaries as points (two categories - <= 1000 CBGs and > 1000 CBGa per community). The service is http://leb.epa.gov/arcgis/rest/services/Other/Community_points. I did the break at 1000 as a subtle reminder of the time it takes for larger number of CBGs to load.

The attributes include the Community, CommST, and BG_count (metadata URL is there, but it's not complete for all fields.

**Comment by brosenbaum** [comment]
As per our discussion on the call 3/16, I have changed the service to switch from points at the national scale to community boundaries when zoomed in. Renamed the service to something more meaningful - https://leb.epa.gov/arcgis/rest/services/Other/Community_Locations. I will add this to the json as a service. 

I know we still need discussion about if this is the way to go, but thought the service might be good for testing. Lots of questions, too - what to do with pop-up. we can populate a field in the service with links that may be needed.

**Comment by torrin47** [comment]
Splitting this into multiple tickets.  This ticket will be used to track progress on adding the service to the boundaries layers list and configuring the basic popup info (the big button will be added programmatically). Coding issues will be tracked in issue...

**Comment by brosenbaum** [comment]
png will be added later - not ready now. so can just add select community to existing pop-up. Need to default the popups enabled "on" in the code and hide/suppress the legend if possible.

Also, I updated the service so the point and poly layers don't overlap.

**Comment by brosenbaum** [comment]
note from Jeremy on infographic they hope to have in the popup -- down the road:

_No work has been done on this yet.  If we do the infographic it will probably be a png, so could we just put a holder png inside the standard popup screen.  For MVP I’d say just the popup with Community name and zoom to is sufficient._  

Although Jeremy says the "zoom to" is sufficient, I believe the intent was to have an option to select the community, too. But maybe the additional button could just open the select community widget?
