### ISSUE TITLE
Jeremy's list of tasks as of March 17, 2017

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#374]
- [x] PBS layer selection Appearance
- [x] Boundaries layer selection Appearance
(NEW ISSUE NEEDED) Put legend in active layer list; move basic legend to mapping tools; would like accordion to open when checked (if possible)
- [x] Remove icons from the Active Layer List
- [x] Tighten up the spacing in the Active Layer List
- [x] Change the default legend size
- [x] Change the X for all widgets to a -- for minimizing

completed:

- [x] Search All working :: Pushed
- [x] Bolder outline for Search Bar :: Pushed
- [x] Default FX for Filter Search: N+C Checked, NO Topics Checked, NO layers displayed :: Pushed
- [x] For greyed out topics, grey out words too :: Pushed 
- [x] Collapsible sections in filter/search :: Pushed

**Comment by brosenbaum** [comment]
This task is based on Jessica's list she showed on the code call.

**Comment by brosenbaum** [comment]
Jeremy - if you have any changes to push this week, could you please do so before 11am tomorrow (Wed morning) if possible. That way we can integrate with any other changes we are making before Thursday's call. Or, can you let us know what progress you are making on the list above? even a comment back here is fine. thanks

**Comment by brosenbaum** [comment]
note from Jeremy about "Put legend in active layer list; move basic legend to mapping tools; would like accordion to open when checked (if possible)":

 I have a small bit of css and javascript that can help.  I’ll just include them here.  

My workaround to not have the layername appear twice
`.jimu-widget-layerList .esriLegendLayer > tbody > tr > td:first-child {
  font-size: 0px;
}`

To change the width of col1 in the layerlist (so the drop down icon and checkbox will be on same line when there is a long layer name)

`var col1_width = 20 + ((level + 1) * 15);
layerTdNode = domConstruct.create(‘td’, {
  ‘class’: ‘col col1’,
  ‘width’: col1_width + ’px’
}, layerTrNode);`

**Comment by jeremybaynes** [comment]
Issue completed.  OK to close.
