### ISSUE TITLE
Symbology widget should add definition expression to getStatistics when community is selected

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#391]
This is a reversal of previous functionality, though I believe it was implemented at some point. Goal is for only community data to be used for dynamic classification and histogram.  Removal of the global definition expression is tracked in ticket #390.

**Comment by David-Yarnell** [comment]
I'm unclear on this change. Right now it looks like the Community selection widget is applying the definition expression. Are we now changing that so that the table widget and the dynamic symbology widget are now applying the definition query?

**Comment by brosenbaum** [comment]
If I follow Torrin's thinking here I'd say "yes" to your question. He has three tickets - #390 to remove the global def. query and then #392 and this issue to add the specific selected community's definition back in to each.

**Comment by brosenbaum** [comment]
David - added something to your "pull" but thought I'd restate here. This may be unrelated to what you did on this but... 

Sue said basically there is weirdness with dyn symb on national layer (for example crop prod/fruit yields layer) - can't get back to default. symbology changes to other and 0 - 100. I saw the same thing.
