### ISSUE TITLE
Add info icons for boundary and people and built spaces layers

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#401]
Per our discussion today - the links should be in the config.json file.  Jeremy may override the button behavior if we get the buttons initialized.

**Comment by Baohong** [comment]
done

**Comment by brosenbaum** [comment]
Have we added the i button to the Boundaries? I'm not seeing it - but again, it could be me! 
this is now displaying info at the service level, not the layer level. is that an issue? I'm compiling the DFS into a new version of the spreadsheet.

**Comment by Baohong** [comment]
There is no code for i button to Boundaries yet. I will add code later, maybe early next week.
