### ISSUE TITLE
All "dynamic" maps loading as soon as one is selected.

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#406]
#402 This issue Torrin added text to read the type of service that I put in the excel database. It's working, but now when one layer is selected that is dynamic, all dynamic layers are added at the same time. 

One layer to add/test is search for IUCN - select the first record - "IUCN Category".

All sorts of data are added to the layer list. Any thoughts?

**Comment by brosenbaum** [comment]
from Jessica:

_we noticed the “add all” behavior when any data layer from the search/filter was added to the active layer list._ 

_I believe Jeremy found a quick fix for that issue that he was going to send over in the morning if that’s helpful._

**Comment by jeremybaynes** [comment]
Adding the option for feature, dynamic, or tiled in the spreadsheet/config.json file seems to be the culprit.  I'm not sure what is happening after that point in the JS to cause the error but setting all the datasets type to FEATURE in the JSON seems to correct the problem (i.e., layerJSON['type'] = 'FEATURE')

Additionally, the tiled service links are missing because of adding the yes/no tileLink column.  Fixed for now and pushed.

**Comment by brosenbaum** [comment]
Hi jeremy - this is something we need to work on from a different angle. we're not getting some layers because they are actually tiled or dynamic services - not working with them as feature services at this time.  And, the tileLink has to do with the national metrics not tiled services. The pull request was not merged.

**Comment by jeremybaynes** [comment]
Sounds good to me.  I knew there had to be more to the dynamic/tiled/feature.

As for the tileLink, the script is looking in that column for the path to the service cache, but the link is in tileURL

**Comment by brosenbaum** [comment]
yeah - there was a method to our madness! and thanks for the comment about the tileURL vs tileLink - I'll make sure to check that out.

**Comment by brosenbaum** [comment]
ummm.... I will make a different pull request - we need to take some of the changes back, but I don't want to modify the scripts as you have... Other problems arose.
