### ISSUE TITLE
New Biodiversity icon is not changing color for biodiversity layers. 

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#425]
the turtle is not changing colors like the other benefit category icons. Add "NLCD" in the search bar - these should all be Biodiversity BCs.

**Comment by brosenbaum** [comment]
Jeremy - if you could take a first look at this..

**Comment by jeremybaynes** [comment]
Biodiversity column missing from spreadsheet formula.  Added:
IF(LEN(TRIM(K2))=0,"",$K$1 & " - " & K2 & "; ") & 
to column Z and copied results to column T
ran Python script and copied config.json to LocalLayer

**Comment by brosenbaum** [comment]
we pushed changes to spreadsheet - we now have green turtles!!!
