### ISSUE TITLE
Metadata link does not appear to be working for some folks in layer list menu.

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#430]
Thought I put this in as an issue - but can't find it (Torrin, I know you will if it's here...)

**Comment by brosenbaum** [comment]
oh, sent an email.... appears it's the "national" data that is having issues. Baohong said she would look at the error in the image below

![image](https://cloud.githubusercontent.com/assets/6422486/25451333/ad2ba868-2a76-11e7-9951-fd21c545c2ed.png)

**Comment by brosenbaum** [comment]
So, there is the national issue with the metadata link and also a problem when "All communities" are selected.

Need to talk with Annie/others about metadata to point to when we have "all communities" selected - currently, we only have the individual community records by attribute sets (as per seen in the UUID json file. What to do....general EDG metadata search string?

**Comment by brosenbaum** [comment]
Hi Baohong - I am going to add a specific URL string for "All Communities" tables - it will be a search of the EDG for key words. 
I'll fill in the UUID table with an all community column and the string will look something like this:

https://edg.epa.gov/metadata/rest/find/document?f=searchpage&searchText=keywords:"enviroatlas"+"itree"

**Comment by Baohong** [comment]
Ok.
