### ISSUE TITLE
National Demographics from geodata web service are not carrying through hatch symbology

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#450]
Symbology from service https://geodata.epa.gov/arcgis/rest/services/OEI/ACS_Demographics_by_Tract_2008_2012/MapServer is not drawing the larger value cross-hatch symbology as seen here:
![image](https://cloud.githubusercontent.com/assets/6422486/25630286/6d323dc6-2f21-11e7-8022-25c1108cdca3.png)

The symbology shows as a single hatch pattern. 

Issue with the WAB? works for web map.

**Comment by torrin47** [comment]
Looks to be issue with client-side symbology, need to confirm with esri and explore workarounds.

**Comment by torrin47** [comment]
Symbology might need to be set by code, since service isn't advertising correct crosshatch for web:
https://developers.arcgis.com/javascript/3/samples/playground/main.html#/config=symbols/SimpleFillSymbol.json

**Comment by torrin47** [comment]
Confirmed the same renderer problem at 10.5.  Submitted ticket to Esri: #01929777.  We'll see what they say.

**Comment by torrin47** [comment]
Esri confirmed this as a bug: #BUG-000105169. Don't expect a quick resolution, will need to investigate workarounds.

**Comment by torrin47** [comment]
Meeting decision: grab data and MXD from CFERST service, switch symbology, and publish as EA layer.
