### ISSUE TITLE
ECAT widget updates and comments

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#454]
- [x] with Async request - how do you know it's still working? can we pop up a notice if it fails or completed? possible enhancement?

- [x] "i" button, when clicked does not display properly with default window size. "OK" button not visible to release the notification. Make full screen instead  of inside widget? BUG...

- [ ] text revisit - Need to figure out any changes before release - will add comment for any text changes.

**Comment by Baohong** [comment]
Item #1: a piece of text could be added at the right-hand side of the spinning wheel when ECAT is successfully completed or fails.

Item #2: I have no problem displaying the message window. "OK" button is always visible at the bottom. I have tested against firefox, chrome and IE. Could Torrin and Daivd test again?

But I have one problem of ECAT: in firefox, text "EnviroAtlas Change Analysis Tool (ECAT)" is not showing in drawer "Analytical Tools". It is blank with ECAT item. Chrome and IE works fine.  Does anybody else have the same problem with firefox?

**Comment by David-Yarnell** [comment]
I just tested Item #2 in Chrome it looks good, in Firefox it looks fine but in IE the message window is cutoff.

I confirm that the text "EnviroAtlas Change Analysis Tool (ECAT)" is not displaying in firefox unless I make drawer widget window wider.

**Comment by Baohong** [comment]
Thanks, David. I will make ECAT widget window a little bit wider on opening.
for Item #2, it seems that in IE the splash is constrained inside ECAT window. I will try to use showModalDialog instead of splash screen. Since original code works fine for chrome and firefox, we can still keep splash screen for them.

**Comment by Baohong** [comment]
I have managed to show splash screen outside of ECAT widget window, but the OK button is not working properly. So I use showModalDialog instead of splash screen for IE only.
