### ISSUE TITLE
Change symbology issue - try 2

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#460]
- [x] weirdness with dyn symb on national crop prod/fruit yields layer - can't get back to default
- [x] how to deal with flag values in dynamic symbology? day cares ,25 green (- 99999, -8888888) - ignore?
- [x] Many national layers are returning 0-100 and "other" for change symbology - any classification - only when a community is selected (if all communities are selected, it works fine).
- [x] The reset button isn't working for national layers.
- [x] Changing symbology for an imported shapefile doesn't work (We already have ticket #133 in the Icebox requesting this functionality - is this something that should work or should we address this by removing "Change Symbology" from TOC context menu for imported shapefiles?)

**Comment by David-Yarnell** [comment]
I believe that I can reach back to the config file with the default symbology to fix this.

**Comment by torrin47** [comment]
Consensus on null values is to apply definition expression excluding -99999 and -888888 from community layers whenever a custom symbology is chosen.
