### ISSUE TITLE
Improve HUC Nav tool to incorporate look and feel from Raindrop widget

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#468]
The UX design of the Raindrop widget is very polished and should be easy to incorporate into the HUC Nav tool.  This includes:

- [ ] Move the "Select a Point" and "Clear" buttons to the top with the big grey look
- [ ] Add the three tabs (About, Results, and Settings)
- [ ] Text for the About tab is: "This tool is an initial release (prototype) of the national HUC catchments and is still under review and testing. The Navigate HUC 12 Catchments Tool allows users to click on any location in the conterminous US, navigate to the nearest stream, and navigate upstream or downstream HUCs within the stream network. On the Filter and Search page of this tool, users may choose to select HUCs either by filtering for distance (stream kilometers) or by time of travel (days) from an interactively-selected point. Click on Select Point to begin using this tool. For additional guidance on this tool, please see the About EnviroAtlas document - accessible from the map viewer Help button."
- [ ] The Results tab should display what's currently in the "Polygons plotted" textarea
- [ ] The other elements should be placed on the "Settings" tab
- [ ] The "Distance or Time of Travel" choice should be removed because Time is unsupported for now.
- [ ] Remove sentence "This tool is a prototype for testing only." from Raindrop Widget.

**Comment by Baohong** [comment]
done
