### ISSUE TITLE
Hydrologic Unit Code (HUC) Boundaries and labels layer doesn't load

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#497]
Diagnose/fix.

**Comment by torrin47** [comment]
Popup configuration for HUC8 has stray } in fieldname property for HUC4,
`"fiel}dName": "HUC4",`
which is causing this problem. Removing the } resolves the issue - need to make sure it's addressed at the spreadsheet level, assigning to @brosenbaum

**Comment by brosenbaum** [comment]
done...
