### ISSUE TITLE
Update "upload data" widget to not include "Change appearance" entry in Layer List widget

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#506]
Adding custom symbology to uploaded data (shapefiles and csvs) is addressed in #133, currently in the icebox, not part of MVP.  Not sure whether layerlist widget menu choices are controlled by uploadData widget or layerList widget, but we should remove this menu option until the functionality is supported for this data type.

**Comment by Baohong** [comment]
done.

**Comment by torrin47** [comment]
Same change needs to occur on all enviroatlas dynamic and tile layers, so "Change Appearance" only occurs for Feature Layers.
