### ISSUE TITLE
Raindrop Tool - misc. questions

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#519]
- [x] only one selection/point shown at a time - flex kept several on screen. Can we change this so multiple points are shown? 

- [x] Also question about the the calculation differences between "total" and "path" distance  - they are always the same.  Remove Total distance and only show path.

**Comment by David-Yarnell** [comment]
@spierson Below is a link to some of the documentation that vaguely defines Path distance compared to total distance. You will have to scroll about 3/4 of the way down the page to "Output Return Object".

https://www.epa.gov/waterdata/point-indexing-service
