### ISSUE TITLE
Functionality issue between Raindrop/HucNav/Elevation

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#576]
When one of these tools is activated (say, Raindrop has several points added) and either HUC Nav or Elevation is opened and activated, the cursor still draws raindrop squiggles. I think the same issue is seen for all the other permutations of these three tools.

Would like that when all tools are open, if any one of the three tools is activated, that the graphics for the other two remain (if the tool is not cleared) and the other two tools are deactivated (not closed).

**Comment by Baohong** [comment]
It is working that if any one of the three tools is activated the other two tools are deactivated. But currently, HucNavigation will clear all graphics (including the graphic result of other two tools). I will work to solve this problem, hopefully finish before the end of today.
