### ISSUE TITLE
Design new icon for raindrop tool

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#94]
Make it fun!

**Comment by brosenbaum** [comment]
![raindroptool_icon](https://cloud.githubusercontent.com/assets/6422486/24517086/eca3f338-154a-11e7-92a7-8e90d75a5f71.png)

**Comment by brosenbaum** [comment]
Icon loaded but is white so not visible. here is the address:
https://cloud.githubusercontent.com/assets/6422486/24517086/eca3f338-154a-11e7-92a7-8e90d75a5f71.png

**Comment by brosenbaum** [comment]
#387
